### Create user
POST {{registrationUrl}}/registration
Content-Type: application/json

{"name": "Sally"}

### Get user
GET {{registrationUrl}}/users/4

### Get account
GET {{registrationUrl}}/accounts?ownerId=4

### Create project
POST {{registrationUrl}}/projects
Content-Type: application/json

{"name": "Basket Weaving III", "accountId": 4}

### Get projects
GET {{registrationUrl}}/projects?accountId=4

### Create allocation
POST {{allocationsUrl}}/allocations
Content-Type: application/json

{"projectId": 4, "userId": 4, "firstDay": "2015-05-17", "lastDay": "2015-05-18"}

### Get allocations
GET {{allocationsUrl}}/allocations?projectId=4

### Create story
POST {{backlogUrl}}/stories
Content-Type: application/json

{"projectId": 4, "name": "Find some reeds"}

### Get stories
GET {{backlogUrl}}/stories?projectId=4

### Create timesheet
POST {{timesheetsUrl}}/time-entries/
Content-Type: application/json

{"projectId": 4, "userId": 4, "date": "2015-05-17", "hours": 6}

### Get timesheets
GET {{timesheetsUrl}}/time-entries?userId=4

###
